### ISSUE TITLE
Convert directory command doesn't work, throws no errors.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChromeLabs/extension-manifest-converter#16]
I tried running this against a directory containing MV2 source files:

`python3 emc.py dir/path/`

Nothing in the directory changes. Here's the extension I'm trying to convert:

https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/_archive/mv2/howto/sandbox

**Comment by solomonkinard** [comment]
I just ran it successfully using the steps that you provided. The new extension is converted and resides in sandbox_delete. What's different about your setup?

 % python3 emc.py /tmp/chrome-extensions-samples/_archive/mv2/howto/sandbox
/tmp/chrome-extensions-samples/_archive/mv2/howto/sandbox
Changing manifest_version to 3
Changed to chrome.action in manifest.json
Changed to chrome.action in .js files
Updating web_accessible_resources
Converted extension into: /tmp/chrome-extensions-samples/_archive/mv2/howto/sandbox_delete

**Comment by jpmedley** [comment]
I wasn't looking for it in sandbox/_delete and failed to notice that it told me to look there. Sorry about that.
