### ISSUE TITLE
Mv3 to Mv2

### ISSUE THREAD

**Issue by i1Fury** [GoogleChromeLabs/extension-manifest-converter#9]
Any chance someone can either fork this or add the option to convert mv3 to mv2 for cross platform use?

**Comment by dotproto** [comment]
The project already supports converting Manifest V3 extensions to Manifest V2. To see this in action, run the tool against the [`test32webAccessibleResources`](https://github.com/GoogleChromeLabs/extension-manifest-converter/tree/main/tests/test_convert/test32webAccessibleResources) directory. 

```bash
$ python3 emc.py tests/test_convert/test32webAccessibleResources
```

**Comment by sydia1103** [comment]
> The project already supports converting Manifest V3 extensions to Manifest V2. To see this in action, run the tool against the [`test32webAccessibleResources`](https://github.com/GoogleChromeLabs/extension-manifest-converter/tree/main/tests/test_convert/test32webAccessibleResources) directory.
> 
> ```shell
> $ python3 emc.py tests/test_convert/test32webAccessibleResources
> ```

Actually, it doesn't convert it properly. It only changes the manifest version to v2 but changes nothing else, which means it is still technically a v3 extension. Hope this can be added in the future.

**Comment by solomonkinard** [comment]
Yes, MV2 to MV3 conversions already have limited support. Why would you want to fully support going from the current version to the previous version? Anyone can implement that and request a merge if they find it useful.

**Comment by solomonkinard** [comment]
Yes, MV3 to MV2 conversions already have limited support. Why would you want to fully support going from the current version to the previous version? Anyone can add more MV3 to MV2 support and request a merge if they would find it useful.

**Comment by Pandapip1** [comment]
Firefox uses MV2 for various reasons (primarily, it not being an official standard and it being continually updated by Google). I would prefer to write my extensions in MV3 however because I think the format is cleaner. As such, there is a good use case for this.
